### ISSUE TITLE
Can't compile on 1.5

### ISSUE THREAD

**Issue by teburd** [autumnai/phloem#12]
Looks like this doesn't compile with 1.5, is nightly a requirement, if so, which version, as the latest nightly also fails to build it.

1.5.0

``` sh
  Compiling phloem v0.3.0
/home/tburdick/.multirust/toolchains/1.5.0/cargo/registry/src/github.com-0a35038f75765ae4/phloem-0.3.0/src/lib.rs:20:1: 20:30 error: #[feature] may not be used on the stable release channel
/home/tburdick/.multirust/toolchains/1.5.0/cargo/registry/src/github.com-0a35038f75765ae4/phloem-0.3.0/src/lib.rs:20 #![feature(clone_from_slice)]
                                                                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

nightly

``` sh
/home/tburdick/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/phloem-0.3.0/src/blob.rs:29:5: 29:28 error: unresolved import `co::libraries::blas::*`. Could not find `libraries` in `co` [E0432]
/home/tburdick/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/phloem-0.3.0/src/blob.rs:29 use co::libraries::blas::*;
                                                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~
/home/tburdick/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/phloem-0.3.0/src/blob.rs:29:5: 29:28 help: run `rustc --explain E0432` to see a detailed explanation
/home/tburdick/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/phloem-0.3.0/src/blob.rs:30:38: 30:43 error: unresolved import `co::libraries::numeric_helpers::Float`. Could not find `libraries` in `co` [E0432]
/home/tburdick/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/phloem-0.3.0/src/blob.rs:30 use co::libraries::numeric_helpers::{Float, cast};
                                                                                                                                                             ^~~~~
/home/tburdick/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/phloem-0.3.0/src/blob.rs:30:38: 30:43 help: run `rustc --explain E0432` to see a detailed explanation
/home/tburdick/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/phloem-0.3.0/src/blob.rs:30:45: 30:49 error: unresolved import `co::libraries::numeric_helpers::cast`. Could not find `libraries` in `co` [E0432]
/home/tburdick/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/phloem-0.3.0/src/blob.rs:30 use co::libraries::numeric_helpers::{Float, cast};
                                                                                                                                                                    ^~~~
/home/tburdick/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/phloem-0.3.0/src/blob.rs:30:45: 30:49 help: run `rustc --explain E0432` to see a detailed explanation
error: aborting due to 3 previous errors
Build failed, waiting for other jobs to finish...
Could not compile `phloem`.

To learn more, run the command again with --verbose.
```

**Comment by MichaelHirn** [comment]
Hi :wave: 

It doesn't compile because of the latest version of [Collenchyma](https://github.com/autumnai/collenchyma) which introduces breaking changes. The Rust version shouldn't be a problem. Collenchyma should build on stable.

Phloem will be replaced in the next couple of days though. [Leaf](https://github.com/autumnai/leaf) will use Collenchyma's [SharedTensor](https://github.com/autumnai/collenchyma/blob/tensor/src/tensor.rs) (tensor branch) and move the Blob (a super thin layer, that holds two SharedTensors; one for data the other for diffs) into Leaf directly.

So dependent on how you would like to use it, you might use those instead. Let me know if that makes sense.

**Comment by teburd** [comment]
That makes sense, I'll just wait for the fixes then

**Comment by MichaelHirn** [comment]
@bfrog We just released [Collenchyma 0.0.6](github.com/autumnai/collenchyma) together with collenchyma-blas 0.1.0 which now supports the SharedTensor.

This is now more powerfull then Phloem's Blob, and this repo is therefore deprecated and all future implementations for an n-D array for cross-device computation will happen on Collenchyma's SharedTensor.

I close this issue for now, but don't hesitate to reopen it for further questions.
